@startuml

autonumber

actor "Doctor" as doc

title "PATCH Medical Record"

box "<<Backoffice Module Node>>" #LightBlue
participant MedicalRecordRoute as route
participant MedicalRecordController as controller
participant MedicalRecordService as service
participant MedicalRecordRepo as repo
participant MedicalRecordSchema as schema
end box

doc -> route: PATCH /medical-record/:medicalRecordCode\n{body: {...}}
route -> controller: updateByPatientId(medicalRecordCode, body)
controller -> service: updateByPatientId(medicalRecordCode, body)
service -> repo: findByPatientId(medicalRecordCode)
repo -> schema: findOne({medicalRecordCode})
schema --> repo: MedicalRecord
repo --> service: MedicalRecord
service -> repo: updateByPatientId(medicalRecordCode, updateData)
repo -> schema: findOneAndUpdate({medicalRecordCode}, {...}, options)
schema --> repo: Updated MedicalRecord
repo --> service: Updated MedicalRecord
service --> controller: Updated MedicalRecord
controller --> route: Updated MedicalRecord
route --> doc: HTTP 200 {record: Updated MedicalRecord}

@enduml
