@startuml

actor "Doctor" as doctor

participant ":SARM" as sys

activate doctor

doctor -> sys : requests new operation

activate sys 

alt success

sys --> doctor : confirms success

else failure

sys --> doctor : throws error message


end


@enduml