@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Admin" as adm


participant ControllerOperationRequest as ct
participant CreateOperationRequestDTO as cdto
participant AppServiceOperationRequest as service
participant OperationRequestBuilder as builder
participant MedicalRecordNumber as mrn
participant LicenceNumber as ln
participant OperationType as op
participant Name as name
participant RequiredStaffBySpecialization as rss
participant EstimatedDuration as ed
participant DeadlineDate as dd
participant Priority as pr
participant OperationRequest as op
participant OperationRequestMapper as mapper
participant DataOperationRequest as data
participant OperationRequestRepository as repository
participant BackofficeAppDbContext as db
adm -> ct: POST [FormBody]


activate ct
ct -> cdto : [FormBody] into cDTO
ct -> service : RegisterOperationRequest(cDTO)
activate service

service -> mrn : new Instance(cDTO.MedicalRecordNumber)
service -> ln : new Instance(cDTO.LicenceNumber)
service -> name : new Instance(cDTO.OperationName)
service -> rss : new Instance(cDTO.RequiredStaffSpecialization)
service -> op : new Instance(name,requiredStaffBySpecialization,estimatedDuration)
service -> dd : new Instance(cDTO.DeadlinesDate)
service -> pr : new Instance(cDTO.Priority)
service -> builder : new Instance(MedicalRecordNumber,LicenceNumber,OperationType,DeadlineDate,Priority)
activate builder
service -> builder : Build()
builder -> op : new Instance(MedicalRecordNumber,LicenceNumber,OperationType,Deadline,Prioriry)
builder --> service : operationRequest
deactivate builder
service -> mapper : ToDataModel(operationRequest)
activate mapper
mapper -> data : new Instance(operationRequest)
mapper --> service : operationDataModel

service -> repository : Add(operationDataModel)
activate repository
repository -> db : OperationRequests.Add(operationDataModel)
activate db
repository -> db : SaveChangesAsync()
deactivate db
repository -> mapper : FromDataModelToDomain(operationDataModel)
mapper --> repository : operation
service -> mapper : toDTO(operationDataModel)
mapper --> service : operationDTO
deactivate mapper



deactivate repository
service --> ct : DTO





ct --> adm : 201 STATUS response





@enduml