@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Administrator" as admin


box "<<Context (C4)>>\n Surgical Appointment and Resource Management"
participant Visualization as ui <<Container(C4)>>
participant Backoffice as bo <<Container(C4)>>


activate admin

admin -> ui : Asks to edit patient profile

activate ui

ui -> bo : PUT edit Patient 

activate bo

alt success

bo --> ui : Status Code 200, Patient edited

ui --> admin : Confirms editing success

else failure

bo --> ui:  Client/Server error Status Code

deactivate bo

ui --> admin: Informs editing failure

deactivate ui

end


@enduml