@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Admin" as adm


box "<<Context (C4)>>\n Surgical Appointment and Resource Management"
participant Visualization as ui <<Container(C4)>>
participant Backoffice as bo <<Container(C4)>>


activate adm

adm -> ui : Asks to register new backoffice user

activate ui

ui -> bo : POST register backoffice user 

activate bo

alt success

bo --> ui : Status Code 201, User created

else failure

bo --> ui:  Client/Server error Status Code

end

deactivate bo







@enduml