@startuml
'https://plantuml.com/sequence-diagram

autonumber


actor "Administrator" as admin

participant ":SARM" as sys

activate admin

admin -> sys : Asks to create a new allergy

activate sys

sys --> admin : Shows the allergy form

admin -> sys: Fills the form and submits

alt success

sys --> admin : Informs creation was success

else failure

sys --> admin : Informs creation was unsuccessful

deactivate sys
deactivate admin

end

@enduml