@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Admin" as adm

participant ":SARM" as sys


activate adm

adm -> sys : Asks to register new backoffice user

activate sys

alt success

    sys --> adm : Confirms registration success

else failure

    sys --> adm : Informs registration was unsuccessful

deactivate sys
    
deactivate adm

end

@enduml