@startuml

package OperationRequestAggregate #LightBlue {
    object OperationRequest<<Entity Root>> 
    object DeadLine <<ValueObject>>{
        <<deadline: Date>>
    }
    object Priority <<ValueObject>>{
        <<priority: int>>
    }
}

package   OperationTypeAggregate #Brown {
    object OperationType<<Entity Root>>
    object Name <<ValueObject>>{
        <<name: string>>
    }
    object RequiredStaffBySpecialization <<ValueObject>>{
        
    }

    object EstimatedDuration <<ValueObject>>{
        <<hour: byte>>
        <<minute: byte>>
        <<second: byte>>
    }
}

package  AppointmentAggregate #SeaGreen {
    object Appointment<<Entity Root>>
    object DateTime <<ValueObject>>{
        <<date: Date>>
    }
    object Status{
        <<scheduled: bool>>
        <<completed: bool>>
        <<canceled: bool>>

    }
}

package  UserAggregate #IndianRed{

    object Role<<ValueObject>>{
        <<description : string>>
    }
    object FullName<<ValueObject>>{
        <<firstName : string>>
        <<lastName : string>>
    }
    object Username<<ValueObject>>{
        <<description : string>>
    }
    object Email <<ValueObject>> {
        <<description : string>>
    }
    object User<<Entity Root>>

}

package StaffAggregate #OrangeRed {
    object Staff<<Entity Root>> 
    object LicenseNumber<<ValueObject>>{
        <<id:int>>
    }
    object Specialization<<ValueObject>>{
        <<description:string>>
    }
    object AvailabilitySlots<<ValueObject>>{
        <<description:string>>
    }

}

package PatientAggregate #SpringGreen {
    object Patient<<Entity Root>>
    object DateOfBirth <<ValueObject>>{
        <<date: Date>>
    }

    object Gender <<ValueObject>>{
        <<gender : bool>>
    }
    object MedicalRecordNumber <<ValueObject>>{
        <<long :number>>
    }
    object MedicalConditions <<ValueObject>>{
        <<description:string>>
    }
    object EmergencyContact <<ValueObject>>{
        <<email:Email>>
        <<phoneNumber:PhoneNumber>>
    }
    object AppointmentHistory <<ValueObjects>>{
        <<pastAppointments : List<Appointment>>>
        <<incomingAppointments : List<Appointment>>>
    }


}




package   SurgeryRoomAggregate #BlueViolet{
    object SurgeryRoom<<Entity Root>>
    object RoomNumber<<ValueObject>>{
        <<description : string>>
    }
    object Type <<ValueObject>>{
        <<description : string>>
    }
    object Capacity <<ValueObject>>{
        <<capacity: long>>
    }

    object AssignedEquipment <<ValueObject>>{
        << equipment: List<Equipment> >>
    }

    object CurrentStatus <<ValueObject>> {
        <<available : bool>>
        <<ocupied : bool>>
        <<underMaintenance : bool>>
    }

    object MaintenanceSlots <<ValueObject>> {
        <<maintenanceSlots : List<Slots> >>
    }
}

@enduml
