@startuml

actor "Doctor" as doctor

participant ":SARM" as sys

activate doctor

doctor -> sys : update operation

activate sys 

alt success

sys --> doctor : 200 OK Status

else failure

sys --> doctor : 204 No Content / 400 Bad Request / 404 Not Found


end


@enduml