@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Administrator" as admin


box "<<Context (C4)>>\n Surgical Appointment and Resource Management"

participant Visualization as ui <<Container(C4)>>
participant Backoffice as bo <<Container(C4)>>

activate admin

admin -> ui : Asks to register patient profile

activate ui

ui --> admin : Shows the form

admin -> ui: Fills the form and submits


ui -> bo : POST register Patient 

activate bo

alt success

bo --> ui : Status Code 201, Patient created

ui --> admin : Confirms registration success

else failure

bo --> ui:  Client/Server error Status Code

deactivate bo

ui --> admin: Informs registration failure

deactivate ui

end


@enduml