@startuml

actor "Doctor" as doctor

participant ":SARM" as sys

activate doctor

doctor -> sys : delete operation

activate sys 

alt success

sys --> doctor : 200 OK Status

else failure

sys --> doctor : 204 No Content/404 Not Found


end


@enduml