@startuml
'https://plantuml.com/sequence-diagram

autonumber



box "<<Container (C4)>>\n Backoffice Web Application"

participant PatientRoute

participant PatientController

participant JsonDTOMapper

participant PatientService

participant PatientMapper

participant Patient

participant IPatientRepository

participant PatientRepository


-> PatientRoute : POST(json)

activate PatientRoute

PatientRoute -> PatientController : createPatient(json)

activate PatientController

PatientController -> PatientController : validate(json)

PatientController -> JsonDTOMapper: mapToDTOPatient(json)

activate JsonDTOMapper



JsonDTOMapper --> PatientController : PatientDTO

deactivate JsonDTOMapper

PatientController -> PatientService : createPatient(PatientDTO)

activate PatientService

PatientService -> PatientMapper : ToDomain(PatientDTO)
 
activate PatientMapper

PatientMapper -> Patient : Patient(...)

activate Patient

Patient --> PatientMapper: patient

deactivate Patient

PatientMapper --> PatientService : patient

deactivate PatientMapper

PatientService -> IPatientRepository : save(patient)

activate IPatientRepository

IPatientRepository -> PatientRepository : save(patient)

deactivate IPatientRepository

PatientService -> PatientMapper : ToDTO(patient)

activate PatientMapper

PatientMapper --> PatientService : patientDTO

deactivate PatientMapper

PatientService --> PatientController : patientDTO

deactivate PatientService

PatientController -> JsonDTOMapper : mapToJsonPatient(patientDTO)

activate JsonDTOMapper

JsonDTOMapper --> PatientController : json

deactivate JsonDTOMapper

PatientController -> PatientController : generateResponse(json)

PatientController --> PatientRoute : response

deactivate PatientController

<-- PatientRoute  : response


@enduml