@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Patient" as patient

participant ":SARM" as sys


activate patient

patient -> sys : Asks to register for the healthcare application

activate sys

alt success

    sys --> patient : Confirms registration success

else failure

    sys --> patient : Informs registration was unsuccessful

deactivate sys
    
deactivate patient

end

@enduml