@startuml
left to right direction
package "User Aggregate"{
entity User {}

class Username <<Value Object>> <<Id>> {
  -username: String
}

enum Role {
ADMIN
DOCTOR
NURSE
TECHNICIAN
PATIENT
}

class Email <<Value Object>> {
  -email: String
}
note bottom: unique
}

User "1" --> "1" Username : has
User "1" --> "1" Role : has
User "1" --> "1" Email : has

package "Patient Agreggate" {
entity Patient {}

class FirstName <<Value Object>> {
  -firstName: String
}

class LastName <<Value Object>> {
  -lastName: String
}

class MiddleNames <<Value Object>> {
  -middleNames: String
}

class DateOfBirth <<Value Object>> {
  -dateOfBirth: Date
}

class FirstName <<Value Object>> {
  -firstName: String
}

enum Gender {
MALE
FEMALE
OTHER
}

class MedicalRecordNumber <<Value Object>> <<Id>> {
  -medicalRecordNumber: String
}

/'
class Email <<Value Object>> {
  -email: String
}
'/

class PhoneNumber <<Value Object>> {
  -phoneNumber: String
}
note bottom: unique

class MedicalConditionOrAllergy <<Value Object>> {
  -condition: String
}

class EmergencyContact <<Value Object>> {
  -name: String
  -relation: String
  -phoneNumber: String
}
}

Patient "1" --> "1" FirstName : has
Patient "1" --> "1" LastName : has
Patient "1" --> "0..1" MiddleNames : has
Patient "1" --> "1" DateOfBirth : has
Patient "1" --> "1" Gender : has
Patient "1" --> "1" MedicalRecordNumber : has
Patient "1" --> "1" Email : has
Patient "1" --> "1" PhoneNumber : has
Patient "1" --> "*" MedicalConditionOrAllergy : has
Patient "1" --> "*" EmergencyContact : has

package "Staff Aggregate" {
entity Staff {}

/'
class FirstName <<Value Object>> {
  -firstName: String
}
class LastName <<Value Object>> {
  -lastName: String
}
class MiddleNames <<Value Object>> {
  -middleNames: String
}
'/

class LicenseNumber <<Value Object>> <<Id>> {
  -licenseNumber: String
}

class Specialization <<Value Object>> {
  -specialization: String
}

 
/'
class Email <<Value Object>> {
  -email: String
}
'/

class PhoneNumber <<Value Object>> {
  -phoneNumber: String
}


class AvailabilitySlot <<Value Object>> {
  -slot : TimeInterval
}
}

Staff "1" --> "1" FirstName : has
Staff "1" --> "1" LastName : has
Staff "1" --> "0..1" MiddleNames : has
Staff "1" --> "1" LicenseNumber : has
Staff "1" --> "*" Specialization : has
Staff "1" --> "1" Email : has
Staff "1" --> "1" PhoneNumber : has
Staff "1" --> "*" AvailabilitySlot : has

package "Operation Request Aggregate" {
entity OperationRequest {
  -patientId: MedicalRecordNumber
  -doctorId: LicenseNumber
  -operationTypeId: OperationTypeId
}

class OperationRequestId <<Value Object>> <<Id>> {
  -id: Guid
}

class DeadlineDate <<Value Object>> {
  -deadline: Date
}

enum Priority {}
note bottom : "ask client about priorities"
}

OperationRequest "1" --> "1" OperationRequestId : has
OperationRequest "1" --> "1" DeadlineDate : has
OperationRequest "1" --> "1" Priority : has

package "Operation Type Aggregate" {
entity OperationType {}

class OperationTypeId <<Value Object>> <<Id>> {
  -id: Guid
}

class OperationName <<Value Object>> {
  -name: String
}

entity RequiredStaff {
  -specialization: Specialization
  -numberRequired: int
}

class EstimatedDuration <<Value Object>> {
  -duration: TimeSpan
}
}

OperationType "1" --> "1" OperationTypeId : has
OperationType "1" --> "1" OperationName : has
OperationType "1" --> "1+" RequiredStaff : has
OperationType "1" --> "1" EstimatedDuration : has

package "Appointment Aggregate" {
entity Appointment {}

class AppointmentId <<Value Object>> {
  -id: Guid
  -requestId: OperationRequestId
  -roomId: SurgeryRoomId
}

class AppointmentDateTime <<Value Object>> {
  -dateTime: Timestamp
}

enum Status {
SCHEDULED
COMPLETED
CANCELED
}
}

Appointment "1" --> "1" AppointmentId : has
Appointment "1" --> "1" AppointmentDateTime : has
Appointment "1" --> "1" Status : has

package "Surgery Room Aggregate" {
entity SurgeryRoom {
}


class RoomNumber <<Value Object>> <<Id>> {
  -id: Guid
}

enum RoomType {
OPERATING_ROOM
CONSULTATION_ROOM
ICU
}

class Capacity <<Value Object>> {
  -capacity: int
}

class Equipment <<Value Object>> {
  -name: String
}

enum CurrentStatus {
AVAILABLE
OCCUPIED
UNDER_MAINTENANCE
}

class MaintenanceSlot <<Value Object>> {
  -slot : TimeInterval
}
}

SurgeryRoom "1" --> "1" RoomNumber : has
SurgeryRoom "1" --> "1" RoomType : has
SurgeryRoom "1" --> "1" Capacity : has
SurgeryRoom "1" --> "*" Equipment: has
SurgeryRoom "1" --> "1" CurrentStatus : has
SurgeryRoom "1" --> "*" MaintenanceSlot : has


  "Operation Request Aggregate" -[hidden]left- "Operation Type Aggregate"
@enduml