@startuml

actor "Admin" as admin

participant ":SARM" as sys 

activate admin

admin -> sys : Asks to register a new patient profile

activate sys

alt success

    sys --> admin : Confirms registration successfully

else failure

    sys --> admin : Informs registration was unsuccessful

deactivate admin
deactivate sys

end





@enduml