@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Admin" as adm

participant RoutePatient as rt
participant ControllerPatient as ct
participant jsonToDTO as jdto
participant voPatient as vo
participant AppServicePatient as asu
participant UserMapper as ifu
participant "user : User" as u
participant IRepoPatient as iru
participant DomainToData as dtd
participant DataPatient as du
participant IDBDriver as dbd
participant "savedPatient : DataPatient" as sdu
participant "patientSaved : Patient" as us

adm --> rt : POST register new patient profile
activate rt
rt --> ct : createPatient(json)
activate ct
ct --> ct : validate(json)
ct --> jdto : mapToDTOPatient(json)
activate jdto
jdto --> vo : create(json)

deactivate jdto
ct --> asu : createPatient(voPatient)
activate asu
asu --> ifu : create(voPatient)
activate ifu
ifu --> u : create()
deactivate ifu
asu --> iru : save(patient)
activate iru
iru --> dtd : mapToDataPatient(patient)
activate dtd
dtd --> u : getEmail()
activate u
dtd --> u : getUsername()
dtd --> u : getRole()
deactivate u
dtd --> du : create(username, email, role)
iru --> dbd : save(dataPatient)
activate dbd
dbd --> sdu : save(savedPatient)
deactivate dbd
deactivate asu
iru --> dtd : mapToModel(savedPatient)
deactivate iru
dtd --> us
deactivate dtd
activate us
ct --> jdto : mapToJSON(patientSaved)
activate jdto
jdto --> us : getUsername()
jdto --> us : getEmail()
jdto --> us : getRole()
deactivate us
jdto --> dto : create(username, email, role)
activate dto
deactivate jdto
deactivate dto
ct --> rt : return success
rt --> adm : confirm POST success

@enduml