@startuml

package App{
    package Infastructure{
        package Routes{}
        package Persistence{}
    }

    package Interface&Adapters{
        package Controllers{}
        package Repositories{}

    }

    package ApplicationServices{
        package AppServices{}
    }

    package Domain{
        package Aggregates{}
        package ValueObjects{}
        package Services{}
        package Factories{}
        package Repositories{}
    }
}

Routes .down--> Controllers
Repositories .down--> Persistence



@enduml