// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G74.Migrations
{
    [DbContext(typeof(BackofficeAppDbContext))]
    partial class BackofficeAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataOperationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Days")
                        .HasColumnType("int")
                        .HasColumnName("Days");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeadLine Date");

                    b.Property<int>("Hours")
                        .HasColumnType("int")
                        .HasColumnName("Hours");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Licence Number");

                    b.Property<string>("MedicalRecordNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Medical Record Number");

                    b.Property<int>("Minutes")
                        .HasColumnType("int")
                        .HasColumnName("Minutes");

                    b.Property<string>("NameOperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name Operation Type");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Priority");

                    b.Property<string>("RequiredStaffBySpecialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Required Staff By Specialization");

                    b.Property<int>("Seconds")
                        .HasColumnType("int")
                        .HasColumnName("Seconds");

                    b.HasKey("Id");

                    b.ToTable("OperationRequests");
                });

            modelBuilder.Entity("G74.DTO.StaffDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ContactEmail");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LicenseNumber");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("StaffSpecialization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StaffSpecialization");

                    b.HasKey("Id");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("G74.DTO.UserDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<int>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("Role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("G74.DataModel.PatientDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContactInformation");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmergencyContact");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Gender");

                    b.Property<string>("MedicalRecordNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MedicalRecordNumber");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordNumber")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("G74.DataModel.PatientDataModel", b =>
                {
                    b.OwnsOne("G74.Domain.Value_Objects.Patient.DeletionInformation", "DeletionInformation", b1 =>
                        {
                            b1.Property<Guid>("PatientDataModelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DateToBeDeleted")
                                .HasColumnType("datetime2")
                                .HasColumnName("DateToBeDeleted");

                            b1.Property<bool>("ToDelete")
                                .HasColumnType("bit")
                                .HasColumnName("ToDelete");

                            b1.HasKey("PatientDataModelId");

                            b1.ToTable("Patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientDataModelId");
                        });

                    b.Navigation("DeletionInformation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
