name: Deploy Sarm Application

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      # Backend
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore backend dependencies
        run: dotnet restore src/G74/G74.csproj

      - name: Build backend
        run: dotnet build src/G74/G74.csproj --configuration Release --no-restore

      - name: Test backend
        run: dotnet test src/G74.Tests/G74.Tests.csproj

      - name: Publish backend
        run: dotnet publish src/G74/G74.csproj -c Release -o backend-publish
      
      # Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: G74Frontend
        run: npm install

      - name: Build frontend
        working-directory: G74Frontend
        run: npm run build --prod
      
      # Reorganize files for deployment
      - name: Prepare deployment structure
        run: |
          mkdir -p sarm/backend sarm/frontend
          cp -r backend-publish/* sarm/backend/
          cp -r G74Frontend/dist/g74-frontend/* sarm/frontend/
      
      # Deploy
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: vsgate-ssh.dei.isep.ipp.pt
          username: deployer
          key: ${{ secrets.DEPLOY_KEY }}
          port: 10953
          source: "sarm"
          target: "/var/www/"
          strip_components: 0

      - name: Restart services
        uses: appleboy/ssh-action@master
        with:
          host: vsgate-ssh.dei.isep.ipp.pt
          username: deployer
          key: ${{ secrets.DEPLOY_KEY }}
          port: 10953
          script: |
            sudo systemctl restart g74backend
            sudo systemctl restart nginx