name: Deploy G74 Application

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    # Backend
    - name: Debug DEPLOY_KEY
      run: echo "${{ secrets.DEPLOY_KEY }}" | wc -l
    
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore backend dependencies
      run: dotnet restore src/G74/G74.csproj

    - name: Build backend
      run: dotnet build src/G74/G74.csproj --configuration Release --no-restore

    - name: Test backend
      run: dotnet test src/G74.Tests/G74.Tests.csproj

    - name: Publish backend
      run: dotnet publish src/G74/G74.csproj -c Release -o backend-publish

    # Frontend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install frontend dependencies
      working-directory: G74Frontend
      run: npm install

    - name: Build frontend
      working-directory: G74Frontend
      run: npm run build --prod

    # Deploy
    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: vsgate-ssh.dei.isep.ipp.pt
        username: deployer
        key: ${{ secrets.DEPLOY_KEY }}
        port: 11056
        source: "backend-publish/*,G74Frontend/dist/*"
        target: "/var/www/sarm"
        strip_components: 1
        debug: true  # troubleshooting

    - name: Restart services
      uses: appleboy/ssh-action@master
      with:
        host: vsgate-ssh.dei.isep.ipp.pt
        username: deployer
        key: ${{ secrets.DEPLOY_KEY }}
        port: 11056
        script: |
          sudo systemctl restart g74backend
          sudo systemctl restart nginx