name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Navegar para a pasta correta onde está o .csproj
    - name: Restore dependencies
      run: dotnet restore ./project/src/G74.csproj

    - name: Build
      run: dotnet build ./project/src/SeuProjeto.csproj --no-restore

    - name: Test
      run: dotnet test ./project/src/SeuProjeto.csproj --no-build --verbosity normal
